@PeikkoDesigner_HostAddress = http://localhost:5260


### Send GET request retrieve all users
GET {{PeikkoDesigner_HostAddress}}/api/users/
Accept: application/json

### Send POST request to validate layers
POST http://localhost:5260/api/compute/validate
Content-Type: application/json

{
  "internalLayer": {
    "name": "InternalLayer",
    "x": 0,
    "y": 0,
    "width": 3400,
    "height": 2600,
    "thickness": 120
  },
  "externalLayer": {
    "name": "ExternalLayer",
    "x": -100,
    "y": 0,
    "width": 3600,
    "height": 2800,
    "thickness": 80
  },
  "insulatedLayerThickness": 90,
  "hole": {
    "name": "Hole",
    "x": 1000,
    "y": 800,
    "width": 1200,
    "height": 1200,
    "position": "Both"
  }
}